"""empty message

Revision ID: aac3653ce3d7
Revises: c866f40a40c0
Create Date: 2020-10-11 10:34:28.628908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aac3653ce3d7'
down_revision = 'c866f40a40c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=False))
    op.drop_index('email', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('email', 'user', ['email'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
